### ISSUE TITLE
Hi otilarc

### ISSUE THREAD

**Issue by SteveJayH** [otilrac/firefox-high-gpu#1]
Hi otilarc
I can't know your email of contact info so that I made the issue at one of your repo.
Please check the repo otilarc / FaceAttendance   which the owner is me.
I made some mistake in that repo (some photos are uploaded for testing that code) 
If it is okay, would you please delete that repo from your github???
I'm sorry for this situation.

**Comment by SteveJayH** [comment]
Link for that repo is this : [https://github.com/otilrac/FaceAttendance](https://github.com/otilrac/FaceAttendance)

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by SteveJayH** [comment]
Thank you very much
